return {
  --   'mfussenegger/nvim-lint',
  --   config = function()
  --     local lint = require('lint')
  --     lint.linters_by_ft = {
  --       markdown = { 'vale' },
  --       python = { 'ruff' },
  --     }
  --
  --     lint.linters.ruff.args = { "check", "--force-exclude", "--extend-select", "N", "--quiet", "--stdin-filename", vim.api.nvim_buf_get_name(0), "--no-fix", "--output-format", "json", "-", }
  --     vim.api.nvim_create_autocmd({ 'BufWritePost' }, {
  --       callback = function()
  --         -- try_lint without arguments runs the linters defined in `linters_by_ft`
  --         -- for the current filetype
  --         require('lint').try_lint()
  --
  --         -- You can call `try_lint` with a linter name or a list of names to always
  --         -- run specific linters, independent of the `linters_by_ft` configuration
  --         -- require('lint').try_lint 'cspell'
  --       end,
  --     })
  --   end,
}
